#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# This wizard guides the geospatial-stack install (conda/GRASS need a fresh
# shell, so you run those commands in your own terminal while the wizard waits),
# then captures your NLR API key into .env and runs the data-access smoke test.
# Run it from the repo root:  bash scripts/setup_phase0.sh

if [[ ! -f environment.yml ]]; then
  printf '%s⚠ Run this from the repo root (environment.yml not found here).%s\n' "$YELLOW" "$RESET"
  exit 1
fi

banner "Rooftop Solar — Phase 0 environment setup"

# ── Stage 1 · Miniforge (conda) ───────────────────────────────────────────
stage "Miniforge (conda) — the geospatial-stack package manager"
say "PDAL/GDAL/GRASS install cleanly from conda-forge, not pip. We use Miniforge."
if command -v conda >/dev/null 2>&1; then
  say "$(printf '%s✓ conda already on PATH:%s %s' "$GREEN" "$RESET" "$(conda --version)")"
  say "Nothing to do here — skipping to the env."
else
  step "Opening the Miniforge releases page for reference."
  open_url "https://github.com/conda-forge/miniforge#install"
  say "In YOUR terminal, run the official macOS installer:"
  note '    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"'
  note '    bash "Miniforge3-$(uname)-$(uname -m).sh"'
  say "Accept the license, let it run 'conda init' for zsh, then open a NEW"
  say "terminal (or: source ~/.zshrc) so 'conda' is on PATH."
  note "Alternative if you have Homebrew: brew install miniforge && conda init zsh"
  pause "Press Enter once 'conda --version' works in a new terminal…"
fi

# ── Stage 2 · Create the conda env ─────────────────────────────────────────
stage "Create the 'rooftop-solar' conda env"
say "From the repo root, build the env from environment.yml (this pulls GDAL,"
say "PDAL, geopandas, rasterio, pvlib, etc. — it takes a few minutes)."
say "Use mamba (bundled with Miniforge) — faster resolve + parallel downloads"
say "for a stack this heavy. Plain 'conda' works too if you'd rather."
note "    mamba env create -f environment.yml     # or: conda env create -f …"
note "    conda activate rooftop-solar            # activation stays 'conda'"
note "The env is named 'rooftop-solar' (from environment.yml → name:)."
warn "If the env already exists, update it instead:"
note "    mamba env update -f environment.yml --prune"
pause "Press Enter once the env is created and activated…"

# ── Stage 3 · Editable install of the package ──────────────────────────────
stage "Install the rooftop_solar package (editable)"
say "With the env active, install this repo as an editable package so"
say "'import rooftop_solar' resolves from src/."
note "    pip install -e ."
say "Sanity check (should print with no error):"
note '    python -c "import rooftop_solar; print(rooftop_solar.__file__)"'
pause "Press Enter once the import works…"

# ── Stage 4 · GRASS GIS ────────────────────────────────────────────────────
stage "GRASS GIS — the r.sun radiation engine (Phase-0 exit criterion)"
say "GRASS provides r.sun; it's a SEPARATE system install, callable on PATH."
if command -v grass >/dev/null 2>&1; then
  say "$(printf '%s✓ grass already on PATH:%s %s' "$GREEN" "$RESET" "$(grass --version 2>/dev/null | head -1)")"
else
  say "Recommended on macOS (cleaner than the heavy conda-forge grass package):"
  note "    brew install grass"
  say "No Homebrew? Two alternatives:"
  step "conda-forge:  mamba install -n rooftop-solar -c conda-forge grass"
  step "Official app:  download GRASS.app from grass.osgeo.org, then add its"
  say "  bin to PATH (the app ships a 'grass' launcher)."
  open_url "https://grass.osgeo.org/download/mac/"
  say "Verify it's callable:"
  note "    grass --version"
  pause "Press Enter once 'grass --version' prints a version…"
fi

# ── Stage 5 · NLR API key ──────────────────────────────────────────────────
stage "NLR developer API key (NSRDB + PVWatts v8)"
say "Free key from the National Laboratory of the Rockies (formerly NREL)."
open_url "https://developer.nlr.gov/signup/"
step "Fill in the signup form (name + email); submit it."
step "The API key is shown on the confirmation page AND emailed to you — copy it."
note "Old developer.nrel.gov keys still work, but use the developer.nlr.gov domain."
ask NLR_API_EMAIL "Email you signed up with:"
ask_secret NLR_API_KEY "Paste the API key:"
write_env NLR_API_KEY "$NLR_API_KEY"
write_env NLR_API_EMAIL "$NLR_API_EMAIL"
say "Saved to .env (gitignored — never commit it)."

# ── Stage 6 · Verify — data-access smoke test ──────────────────────────────
stage "Verify — run the data-access smoke test"
say "This confirms every Phase-0 source is reachable: footprints, DSM, imagery,"
say "boundaries, and irradiance (now that the NLR key is set)."
say "With the 'rooftop-solar' env active, run:"
note "    python scripts/check_data_access.py"
say "Expect [ok] on all five. If irradiance still shows [skip], re-check .env."
if command -v conda >/dev/null 2>&1 && confirm "Run it now via 'conda run -n rooftop-solar'?"; then
  conda run -n rooftop-solar python scripts/check_data_access.py || \
    warn "smoke test reported a failure above — see the output for which source."
fi

finish
